# Generated by Django 5.2.7 on 2025-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_customers_customer_rename_products_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
